/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest
 */
public class Prestamos extends javax.swing.JFrame {
    String nomUsuario[] = new String[50];
    String Datos[] = new String[50];
    String cdUsuario[] = new String [50];
    int prestamos [] = new int [50]; 
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Código");
        modelo.addColumn("Tipo de usuario");
        modelo.addColumn("Tipo de texto");
        modelo.addColumn("Prestamos");
        ButtonGroup clasificacion_usuarios = new ButtonGroup();
        clasificacion_usuarios.add(radbtn_empresa);
        clasificacion_usuarios.add(radbtn_monografia);
        tabla_prestamos.setModel(modelo);
        ButtonGroup tipo_texto = new ButtonGroup();
        tipo_texto.add(radbtn_libro);
        tipo_texto.add(radbtn_revista);
        tipo_texto.add(radbtn_monografia);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        radbtn_persona = new javax.swing.JRadioButton();
        radbtn_empresa = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prestamos = new javax.swing.JTable();
        btn_prestamo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_texto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radbtn_monografia = new javax.swing.JRadioButton();
        radbtn_libro = new javax.swing.JRadioButton();
        radbtn_revista = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prestamos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 800, 50));

        jLabel5.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de texto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        radbtn_persona.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_persona.setText("Persona");
        jPanel1.add(radbtn_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 30));

        radbtn_empresa.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_empresa.setText("Empresa");
        jPanel1.add(radbtn_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_codigo.setBackground(new java.awt.Color(97, 212, 195));
        txt_codigo.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_codigo.setBorder(null);
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        tabla_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de usuario", "Codigo", "Prestamos"
            }
        ));
        jScrollPane1.setViewportView(tabla_prestamos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 590, 160));

        btn_prestamo.setBackground(new java.awt.Color(255, 255, 255));
        btn_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseClicked(evt);
            }
        });
        btn_prestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo Prestamo");
        btn_prestamo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, 40));

        volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 50));

        jLabel8.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel8.setText(" Texto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Codigo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(97, 212, 195));
        txt_nombre.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 10));

        txt_texto.setBackground(new java.awt.Color(97, 212, 195));
        txt_texto.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_texto.setBorder(null);
        txt_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_textoActionPerformed(evt);
            }
        });
        txt_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_textoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Tipo de usuario:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        radbtn_monografia.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_monografia.setText("Monografia");
        jPanel1.add(radbtn_monografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        radbtn_libro.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_libro.setText("Libro");
        jPanel1.add(radbtn_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 30));

        radbtn_revista.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_revista.setText("Revista");
        jPanel1.add(radbtn_revista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_textoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_textoActionPerformed

    private void txt_textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_textoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txt_codigo.requestFocus();    
            } 
    }//GEN-LAST:event_txt_textoKeyPressed

    private void btn_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseClicked
        // TODO add your handling code here:
        String botonSeleccionado = "", botonSeleccionado2 = ""; 
        int textencontrado=0, librodisponible[] = new int [50], encontrado =0, pos=0;
        if (radbtn_persona.isSelected()){
             botonSeleccionado = "Persona";
        }else{ 
            if (radbtn_empresa.isSelected()){
            botonSeleccionado = "Empresa";
            }
        }
        if (radbtn_libro.isSelected()){
            botonSeleccionado2 = "libro";
        }else{
            if (radbtn_revista.isSelected()){
            botonSeleccionado2 = "revista";
            }else{
                if (radbtn_monografia.isSelected()){
                botonSeleccionado2 = "monografia";
                }
            }
        }
        if ( "".equals(txt_texto.getText())  || "".equals(txt_codigo.getText()) || "".equals(botonSeleccionado) ||"".equals(botonSeleccionado2)){ 
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_texto.requestFocus();
        }else {
            for (int i = 0; i < AñadirTexto.cont_texto; i++) {
                if (variables.nombre_texto[i].equals(txt_texto.getText())){
                    textencontrado=1;
                    pos=i;
                    if(librodisponible[i]==1){
                        JOptionPane.showMessageDialog(this, "Libro no disponible");
                    }
                }
                if (txt_nombre.getText().equals(variables.nomUsuario[i]) && txt_codigo.getText().equals(variables.codUsuario[i])){
                    encontrado = 1;
                }
            }
            System.out.println("usuario "+ txt_nombre.getText()+ " "+variables.nomUsuario[0] );
            System.out.println("codigo "+ txt_codigo.getText()+ " nuevo codigo "+ variables.codUsuario[0]);
            if(textencontrado == 1 && librodisponible[pos] == 0 && encontrado == 1){
            for (int i = 0; i < variables.cont_usuarios; i++) {
                if(txt_texto.getText().equals(variables.nombre_texto[i]) && librodisponible[i] == 0){
                librodisponible[i]=1;
                Datos[0] = txt_texto.getText();
                Datos[1] = txt_codigo.getText();
                Datos[2] = botonSeleccionado; 
                Datos[3] = botonSeleccionado2;
              if (prestamos[pos] == 0){
                  prestamos[pos] = 0;
                  prestamos[pos] = prestamos[pos] +1;
                  Datos[4] = String.valueOf(prestamos[i]);
              }else{
                      if(prestamos[pos] == 2){
                          JOptionPane.showMessageDialog(this, "Capacidad de prestamos llena");
                      }
              }
              modelo.addRow(Datos);
            }
        }
            }
        if(encontrado == 0){
            JOptionPane.showMessageDialog(this, "Usuario no registrado");
        }
        if(textencontrado == 0){
            JOptionPane.showMessageDialog(this, "Libro no disponible");
        }     
    }//GEN-LAST:event_btn_prestamoMouseClicked
} 
    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        // TODO add your handling code here:
        home menu = new home();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radbtn_empresa;
    private javax.swing.JRadioButton radbtn_libro;
    private javax.swing.JRadioButton radbtn_monografia;
    private javax.swing.JRadioButton radbtn_persona;
    private javax.swing.JRadioButton radbtn_revista;
    private javax.swing.JTable tabla_prestamos;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_texto;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables

     
    
}
