/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest
 */
public class Prestamos extends javax.swing.JFrame {
    String Datos[] = new String[50];
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        
        modelo.addColumn("Nombre del libro");
        modelo.addColumn("Nombre de la persona");
        modelo.addColumn("Tipo de usuario");
        modelo.addColumn("Tipo de texto");
        modelo.addColumn("Prestamos");
        tabla_prestamos.setModel(modelo);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prestamos = new javax.swing.JTable();
        btn_prestamo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_texto = new javax.swing.JTextField();
        btn_actualizarTabla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prestamos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 800, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txt_apellido.setBackground(new java.awt.Color(97, 212, 195));
        txt_apellido.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_apellido.setBorder(null);
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        tabla_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de usuario", "Codigo", "Prestamos"
            }
        ));
        jScrollPane1.setViewportView(tabla_prestamos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 590, 160));

        btn_prestamo.setBackground(new java.awt.Color(255, 255, 255));
        btn_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseClicked(evt);
            }
        });
        btn_prestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo Prestamo");
        btn_prestamo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 200, 40));

        volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 50));

        jLabel8.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel8.setText(" Texto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Apellido:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(97, 212, 195));
        txt_nombre.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 10));

        txt_texto.setBackground(new java.awt.Color(97, 212, 195));
        txt_texto.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_texto.setBorder(null);
        txt_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_textoActionPerformed(evt);
            }
        });
        txt_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_textoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 30));

        btn_actualizarTabla.setBackground(new java.awt.Color(255, 255, 255));
        btn_actualizarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarTablaMouseClicked(evt);
            }
        });
        btn_actualizarTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Actualizar tabla");
        btn_actualizarTabla.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_actualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_textoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_textoActionPerformed

    private void txt_textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_textoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txt_apellido.requestFocus();    
            } 
    }//GEN-LAST:event_txt_textoKeyPressed

    private void btn_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseClicked
        // TODO add your handling code here:
        int textencontrado=0, encontrado = 0, pos= 0;
        int posUser = 0;
        
        if ( txt_texto.getText().equals("")){ 
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_texto.requestFocus();
            
        }else {
            
            for (int i = 0; i < variables.cont_usuarios; i++) {
                if (txt_nombre.getText().equals(variables.nomUsuario[i]) && txt_apellido.getText().equals(variables.apellidoUsuario[i])){
                    encontrado = 1;
                    posUser = i;
                    variables.tipoUsuario_prestamo[i] = variables.tipoUsuario[posUser];
                    System.out.println("Usuario encontrado");
                }
            }
            for (int i = 0; i < variables.cont_texto; i++) {
                
                if (variables.nombre_texto[i].equals(txt_texto.getText())){
                    textencontrado=1;
                    pos=i;
                    variables.tipoTexto_prestamo[i] = variables.tipo_texto[pos];
                    System.out.println("Texto encontrado");
                    if(variables.librodisponible[pos]==1){
                        JOptionPane.showMessageDialog(this, "Libro no disponible");
                    }
                }
                
            }
            if(textencontrado == 1 && variables.librodisponible[pos] == 0 && encontrado == 1){
                variables.cont_prestamos++;
                for (int i = 0; i < variables.cont_prestamos; i++) {
                    if(txt_texto.getText().equals(variables.nombre_texto[i]) && variables.librodisponible[pos] == 0){
                    variables.librodisponible[pos]=1;
                    variables.nomLibro_prestamo[i] = txt_texto.getText();
                    variables.nomUsuario_prestamo[i] = txt_apellido.getText();
                    Datos[0] = variables.nomLibro_prestamo[i];
                    Datos[1] = variables.nomUsuario_prestamo[i];
                    Datos[2] = variables.tipoUsuario_prestamo[i]; 
                    Datos[3] = variables.tipoTexto_prestamo[i];
                    if (variables.prestamos[i] == 0){
                      variables.prestamos[i]++;
                      Datos[4] = String.valueOf(variables.prestamos[i]);
                    }else{
                        if(variables.prestamos[pos] == 2){
                            JOptionPane.showMessageDialog(this, "Capacidad de prestamos llena");
                        }
                  }
                  modelo.addRow(Datos);
                    }
                }
            }
        if(encontrado == 0){
            JOptionPane.showMessageDialog(this, "Usuario no registrado");
        }
        if(textencontrado == 0){
            JOptionPane.showMessageDialog(this, "Libro no disponible");
        }     
    }//GEN-LAST:event_btn_prestamoMouseClicked
} 
    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        // TODO add your handling code here:
        home menu = new home();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void btn_actualizarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarTablaMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < variables.cont_texto; i++) {
            Datos[0] = variables.nomLibro_prestamo[i];
            Datos[1] = variables.nomUsuario_prestamo[i];
            Datos[2] = variables.tipoUsuario_prestamo[i]; 
            Datos[3] = variables.tipoTexto_prestamo[i];
            Datos[4] = String.valueOf(variables.prestamos[i]);

            modelo.addRow(Datos);
        }
                
    }//GEN-LAST:event_btn_actualizarTablaMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_actualizarTabla;
    private javax.swing.JPanel btn_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabla_prestamos;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_texto;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables

     
    
}
