/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest
 */
public class Prestamos extends javax.swing.JFrame {
    public Vector nomUsuario = new Vector();
    public Vector cdUsuario = new Vector();
    String Datos[] = new String[50];
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        initComponents();
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo de usuario");
        modelo.addColumn("Código");
        modelo.addColumn("Prestamos");
        modelo.addColumn("Libros Prestados");
        ButtonGroup clasificacion_usuarios = new ButtonGroup();
        clasificacion_usuarios.add(radbtn_empresa);
        clasificacion_usuarios.add(radbtn_persona);
        tabla_prestamos.setModel(modelo);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        radbtn_persona = new javax.swing.JRadioButton();
        radbtn_empresa = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prestamos = new javax.swing.JTable();
        btn_Verificar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_prestamo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        volver1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prestamos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 800, 50));

        jLabel5.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        radbtn_persona.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_persona.setText("Persona");
        jPanel1.add(radbtn_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        radbtn_empresa.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_empresa.setText("Empresa");
        jPanel1.add(radbtn_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Codigo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(97, 212, 195));
        txt_nombre.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_nombre.setBorder(null);
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        txt_codigo.setBackground(new java.awt.Color(97, 212, 195));
        txt_codigo.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_codigo.setBorder(null);
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 30));

        tabla_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo de usuario", "Codigo", "Prestamos", "Libros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_prestamos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 480, 220));

        btn_Verificar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Verificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VerificarMouseClicked(evt);
            }
        });
        btn_Verificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Verificar Usuario");
        btn_Verificar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 200, 40));

        btn_prestamo.setBackground(new java.awt.Color(255, 255, 255));
        btn_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseClicked(evt);
            }
        });
        btn_prestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo Prestamo");
        btn_prestamo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 200, 40));

        volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volver1MouseClicked(evt);
            }
        });
        jPanel1.add(volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            txt_codigo.requestFocus();    
            } 
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void btn_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseClicked
        // TODO add your handling code here:
        usuarios usuario= new usuarios();
        if ( txt_nombre.getText() == "" || botonSeleccionado() == ""){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_nombre.requestFocus();
        }else {
            Datos[0] = txt_nombre.getText();
            Datos[2] = botonSeleccionado();
            modelo.addRow(Datos);
            nomUsuario.addElement(txt_nombre.getText());
            cdUsuario.addElement(Datos[1]);
            txt_nombre.setText("");
            txt_nombre.requestFocus();
        }
        for (int i = 0; i < 10; i++) {
          
                
            
            
        }
    }//GEN-LAST:event_btn_prestamoMouseClicked

    private void volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volver1MouseClicked
        // TODO add your handling code here:
        home menu = new home();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volver1MouseClicked

    private void btn_VerificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VerificarMouseClicked
        // TODO add your handling code here:
        usuarios usuario =new usuarios();
        if ( txt_nombre.getText() == "" || botonSeleccionado() == ""){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_nombre.requestFocus();
        }
    }//GEN-LAST:event_btn_VerificarMouseClicked
 private String botonSeleccionado(){
        String btn_seleccionado = "";
        if (radbtn_persona.isSelected()){
             btn_seleccionado = "Persona";
        }else if (radbtn_empresa.isSelected()){
            btn_seleccionado = "Empresa";
        }
        return btn_seleccionado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Verificar;
    private javax.swing.JPanel btn_prestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radbtn_empresa;
    private javax.swing.JRadioButton radbtn_persona;
    private javax.swing.JTable tabla_prestamos;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel volver1;
    // End of variables declaration//GEN-END:variables

     
    
}
