/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanes
 */
public class Transacciones extends javax.swing.JFrame {

    /**
     * Creates new form Transacciones
     */
    
    public static ArrayList<String> nombre_editorial = new ArrayList<String>();
    public static ArrayList<String> codigo_editorial = new ArrayList<String>();
    public static ArrayList<String> nombre_autor = new ArrayList<String>();
    public static ArrayList<String> codigo_autor = new ArrayList<String>();
    public static String cod_editorial;
    public static boolean nuevoDato = true;
    String col[] = {"Nombre", "ISBN", "Precio", "Tipo", "Editorial", "Autor", "Estado", "Edad", "Transaccion", "Traslado"};
    DefaultTableModel modelo = new DefaultTableModel(col, 0);
    
            
    public Transacciones() {
        initComponents();
        
        tablaLibros.setModel(modelo);
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_añadirTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_añadirEditorial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_añadirAutor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        volver = new javax.swing.JLabel();
        btn_actualizarTabla = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_añadirTexto.setBackground(new java.awt.Color(255, 255, 255));
        btn_añadirTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirTextoMouseClicked(evt);
            }
        });
        btn_añadirTexto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar un nuevo texto");
        btn_añadirTexto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel1.add(btn_añadirTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 40));

        btn_añadirEditorial.setBackground(new java.awt.Color(255, 255, 255));
        btn_añadirEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirEditorialMouseClicked(evt);
            }
        });
        btn_añadirEditorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingresar nueva editorial");
        btn_añadirEditorial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jPanel1.add(btn_añadirEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, 40));

        btn_añadirAutor.setBackground(new java.awt.Color(255, 255, 255));
        btn_añadirAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_añadirAutorMouseClicked(evt);
            }
        });
        btn_añadirAutor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar nuevo autor");
        btn_añadirAutor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        jPanel1.add(btn_añadirAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, 40));

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 970, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 60, 50));

        btn_actualizarTabla.setBackground(new java.awt.Color(255, 255, 255));
        btn_actualizarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarTablaMouseClicked(evt);
            }
        });
        btn_actualizarTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Actualizar tabla");
        btn_actualizarTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 20));

        jPanel1.add(btn_actualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirTextoMouseClicked
        // TODO add your handling code here:
        AñadirTexto añadir = new AñadirTexto();
        añadir.setVisible(true);
        añadir.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_añadirTextoMouseClicked

    private void btn_añadirEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirEditorialMouseClicked
        // TODO add your handling code here:
        nombre_editorial.add(JOptionPane.showInputDialog("Digite el nombre de la editorial"));
        cod_editorial = generarCodigo(5);
        codigo_editorial.add(cod_editorial);
    }//GEN-LAST:event_btn_añadirEditorialMouseClicked

    private void btn_añadirAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_añadirAutorMouseClicked
        // TODO add your handling code here:
        nombre_autor.add(JOptionPane.showInputDialog("Digite el nombre del autor"));
        codigo_autor.add(generarCodigo(5));
    }//GEN-LAST:event_btn_añadirAutorMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        home menu = new home();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void btn_actualizarTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarTablaMouseClicked
        // TODO add your handling code here:
        if (nuevoDato){
            for (int i = 0; i < AñadirTexto.nombre_texto.size(); i++) {
            String nombre = AñadirTexto.nombre_texto.get(i);
            int precio = AñadirTexto.precio_texto.get(i);
            String tipoTexto = AñadirTexto.tipo_texto.get(i);
            String edit = AñadirTexto.editorial.get(i);
            String aut = AñadirTexto.autor.get(i);
            String estadoTexto = AñadirTexto.estado.get(i);
            int edad = AñadirTexto.edad_texto.get(i);
            String tipoTransaccion = AñadirTexto.tipo_transaccion.get(i);
            String trasladar = AñadirTexto.traslado.get(i);
            String isbn = AñadirTexto.codigo_isbn.get(i);
            
            Object[] datos = {nombre, isbn, precio, tipoTexto, edit, aut, estadoTexto, edad, tipoTransaccion, trasladar};
            
            modelo.addRow(datos);
            nuevoDato = false;
            }
        }
    }//GEN-LAST:event_btn_actualizarTablaMouseClicked

    public static String generarCodigo(int tamañoCodigo) {
        String caracteres = "1234567890";
        StringBuilder cod = new StringBuilder();
        Random rnd = new Random();
        while (cod.length() < tamañoCodigo) {
            int index = (int) (rnd.nextFloat() * caracteres.length());
            cod.append(caracteres.charAt(index));
        }
        String codigo = cod.toString();
        return codigo;
    }
    
    public static String retornarCodigoEditorial(String editorial){
        String codigo = "" ;
        for (int i = 0; i < codigo_editorial.size() ; i++) {
            if (nombre_editorial.get(i).equals(editorial)){
                codigo = codigo_editorial.get(i);
            }
        }
        return codigo;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_actualizarTabla;
    private javax.swing.JPanel btn_añadirAutor;
    private javax.swing.JPanel btn_añadirEditorial;
    private javax.swing.JPanel btn_añadirTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
