/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanes
 */
public class usuarios extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    
    String Datos[] = new String[50];
    String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
    StringBuilder cod = new StringBuilder();
    Random rnd = new Random();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public usuarios() {
        initComponents();
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Código");
        modelo.addColumn("Tipo de usuario");
        tabla_usuarios.setModel(modelo);
        
        ButtonGroup clasificacion_usuarios = new ButtonGroup();
        clasificacion_usuarios.add(radbtn_empresa);
        clasificacion_usuarios.add(radbtn_persona);
        
        btn_guardar.setVisible(false);
        
        for (int i = 0; i < variables.cont_usuarios; i++) {
            Datos[0] = String.valueOf(variables.nomUsuario[i]);
            Datos[1] = String.valueOf(variables.codUsuario[i]);
            Datos[2] = String.valueOf(variables.tipoUsuario[i]);
            modelo.addRow(Datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radbtn_persona = new javax.swing.JRadioButton();
        radbtn_empresa = new javax.swing.JRadioButton();
        btn_guardar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 850, 310));

        jLabel1.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios registrados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 740, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Eliminar usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 200, 40));

        btn_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });
        btn_ingresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar un nuevo usuario");
        btn_ingresar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 200, 40));

        btn_modificar.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        btn_modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modificar usuario");
        btn_modificar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 200, 40));

        jLabel5.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Tipo de usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        txt_usuario.setBackground(new java.awt.Color(97, 212, 195));
        txt_usuario.setFont(new java.awt.Font("Tsukushi A Round Gothic", 0, 14)); // NOI18N
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usuarioMouseClicked(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyPressed(evt);
            }
        });
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        radbtn_persona.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_persona.setText("Persona");
        jPanel1.add(radbtn_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        radbtn_empresa.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 14)); // NOI18N
        radbtn_empresa.setText("Empresa");
        jPanel1.add(radbtn_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Guardar cambios");
        btn_guardar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 20));

        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 200, 40));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMouseClicked
        // TODO add your handling code here:
        txt_usuario.setText("");
    }//GEN-LAST:event_txt_usuarioMouseClicked

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyPressed

    }//GEN-LAST:event_txt_usuarioKeyPressed

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        // TODO add your handling code here:
        int rowCount = modelo.getRowCount();
        
        
        String btn_seleccionado = "";
        if (radbtn_persona.isSelected()){
             btn_seleccionado = "Persona";
        }else if (radbtn_empresa.isSelected()){
            btn_seleccionado = "Empresa";
        }
        
        if ( txt_usuario.getText().equals("") || btn_seleccionado.equals("")){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_usuario.requestFocus();
        }else {
            
            while (cod.length() < 9) {
                int index = (int) (rnd.nextFloat() * caracteres.length());
                cod.append(caracteres.charAt(index));
             }
            String codigo = cod.toString();
            
            variables.nomUsuario[variables.cont_usuarios] = txt_usuario.getText();
            variables.codUsuario[variables.cont_usuarios] = (codigo);
            variables.tipoUsuario[variables.cont_usuarios] = (btn_seleccionado);
            variables.cont_usuarios++;
            
            for (int i = rowCount - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
            
            for (int i = 0; i < variables.cont_usuarios; i++) {
                Datos[0] = String.valueOf(variables.nomUsuario[i]);
                Datos[1] = String.valueOf(variables.codUsuario[i]);
                Datos[2] = String.valueOf(variables.tipoUsuario[i]);
                modelo.addRow(Datos);
            }
            txt_usuario.setText("");
            txt_usuario.requestFocus();
        }
        
        
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tabla_usuarios.getSelectedRow();
        

        if (filaSeleccionada >= 0){
            txt_usuario.setText(tabla_usuarios.getValueAt(filaSeleccionada, 0).toString());
            String btn_seleccionado = tabla_usuarios.getValueAt(filaSeleccionada, 2).toString();

            if (btn_seleccionado.equals("Persona")){
                radbtn_persona.doClick();

            }else if (btn_seleccionado.equals("Empresa")){
                radbtn_empresa.doClick();

            }
            
            btn_guardar.setVisible(true);

        }else {
            JOptionPane.showMessageDialog(this, "Fila no seleccionada");
        }
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tabla_usuarios.getSelectedRow();
        String btn_seleccionado = "";
        if (radbtn_persona.isSelected()){
             btn_seleccionado = "Persona";
        }else if (radbtn_empresa.isSelected()){
            btn_seleccionado = "Empresa";
        }
        
        if ( txt_usuario.getText() == "" || btn_seleccionado == ""){
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
            txt_usuario.requestFocus();
        }else {
            tabla_usuarios.setValueAt(txt_usuario.getText(),filaSeleccionada , 0);
            tabla_usuarios.setValueAt(btn_seleccionado, filaSeleccionada, 2);
            txt_usuario.setText("");
            txt_usuario.requestFocus();
            btn_guardar.setVisible(false);
        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tabla_usuarios.getSelectedRow();
        
        
        if (filaSeleccionada >= 0){
            int result = JOptionPane.showConfirmDialog(null, "Estas seguro de borrar esta fila?", null, JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION){
                modelo.removeRow(filaSeleccionada);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        // TODO add your handling code here:
        home menu = new home();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_guardar;
    private javax.swing.JPanel btn_ingresar;
    private javax.swing.JPanel btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radbtn_empresa;
    private javax.swing.JRadioButton radbtn_persona;
    private javax.swing.JTable tabla_usuarios;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
